[tool.poetry]
name = "xml_scanner"
version = "0.1.0"
description = ""
authors = ["Vitaly Efremov"]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
